name: Test
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Test with Coverage
        run: npm run coverage

      - name: Report Coverage
        uses: codecov/codecov-action@v2
